services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data

  hayhooks:
    build: .
    container_name: hayhooks
    ports:
      - "1416:1416"
    env_file:
      - ".env"

  qdrant-setup:
    build: .
    container_name: qdrant-setup
    depends_on: 
      - qdrant
    env_file:
      - ".env"
    volumes:
      - .:/hayhooks/
    entrypoint: ["python", "/hayhooks/indexing.py"]